// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1B7wswfZw5arkCO8sQklsYUmTQicCq8',
    appId: '1:1098877784292:web:d1c5edccd7ab94a1489cf1',
    messagingSenderId: '1098877784292',
    projectId: 'ecomproject-6d914',
    authDomain: 'ecomproject-6d914.firebaseapp.com',
    storageBucket: 'ecomproject-6d914.firebasestorage.app',
    measurementId: 'G-7JDSF6N1MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreOWPQiKYwTSkHsM-y-MtheUjc6bOCZc',
    appId: '1:1098877784292:android:85b796a2541824f0489cf1',
    messagingSenderId: '1098877784292',
    projectId: 'ecomproject-6d914',
    storageBucket: 'ecomproject-6d914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8pA5i_ZeVr4qPArjhJcwCL_E3vSd8w3E',
    appId: '1:1098877784292:ios:cb20708a7c20eafb489cf1',
    messagingSenderId: '1098877784292',
    projectId: 'ecomproject-6d914',
    storageBucket: 'ecomproject-6d914.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8pA5i_ZeVr4qPArjhJcwCL_E3vSd8w3E',
    appId: '1:1098877784292:ios:cb20708a7c20eafb489cf1',
    messagingSenderId: '1098877784292',
    projectId: 'ecomproject-6d914',
    storageBucket: 'ecomproject-6d914.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1B7wswfZw5arkCO8sQklsYUmTQicCq8',
    appId: '1:1098877784292:web:2bf6f0e75b48ce9c489cf1',
    messagingSenderId: '1098877784292',
    projectId: 'ecomproject-6d914',
    authDomain: 'ecomproject-6d914.firebaseapp.com',
    storageBucket: 'ecomproject-6d914.firebasestorage.app',
    measurementId: 'G-F775M711DE',
  );
}
